### ISSUE TITLE
Error when updating Daddylive channels

### ISSUE THREAD

**Issue by MartinR577** [cabernetwork/provider_video_daddylive#30]
When i refresh daddylive channels it ends with 
"Refresh DaddyLive Channels
Plugin: DaddyLive -- Last ran Never ago, taking"

the log shows
2024-10-17 05:34:03,595-INFO:channels DaddyLive:default 1 Updating Channel 313:Discovery Channel
2024-10-17 05:34:03,794-INFO:channels DaddyLive:default 1 Updating Channel 657:Discovery Family
2024-10-17 05:34:03,993-INFO:channels DaddyLive:default 1 Updating Channel 314:Disney XD
2024-10-17 05:34:03,993-INFO:channels DaddyLive:default 2 New Channel Added 285:Discovery Velocity CA
2024-10-17 05:34:04,389-INFO:channels DaddyLive:default 1 Updating Channel 651:Destination America
2024-10-17 05:34:04,587-INFO:channels DaddyLive:default 1 Updating Channel 652:Disney JR
2024-10-17 05:34:04,587-ERROR:scheduler UNEXPECTED EXCEPTION on GET='str' object has no attribute 'append'
Traceback (most recent call last):
  File "/app/lib/schedule/scheduler.py", line 157, in call_trigger
    results = call_f()
  File "/app/lib/plugins/plugin_obj.py", line 225, in refresh_channels
    return self.refresh_it('Channels', _instance)
  File "/app/lib/plugins/plugin_obj.py", line 248, in refresh_it
    instance.refresh_channels()
  File "/app/lib/plugins/plugin_instance_obj.py", line 152, in refresh_channels
    return self.channels.refresh_channels()
  File "/app/lib/plugins/plugin_channels.py", line 134, in refresh_channels
    ch_dict = self.get_channels()
  File "/app/plugins_ext/provider_video_daddylive/lib/channels.py", line 52, in get_channels
    ch_list = self.get_channel_list()
  File "/app/plugins_ext/provider_video_daddylive/lib/channels.py", line 241, in get_channel_list
    self.groups_other.append(group)
AttributeError: 'str' object has no attribute 'append'
2024-10-17 05:34:05,599-DEBUG:web_handler [192.168.1.177] "GET /api/schedulehtml?Channels=1& HTTP/1.1" 200 -

**Comment by MartinR577** [comment]
this is using the daddylive plugin version 0.1.38 . happening on several systems both windows and in docker. tried both resetting the database and removing the database

**Comment by rocky4546** [comment]
looking into this

**Comment by CheekyMunky81** [comment]
I think there's something new.. tried to open a new issue but saw this:

2024-11-27 03:26:08,687-WARNING:channels DaddyLive channel list is empty from provider, not updating Cabernet

2024-11-27 03:26:08,687-WARNING:plugin_channels Unable to retrieve channel data from DaddyLive:default, aborting refresh

Plugin version 0.1.40

Thanks

**Comment by rocky4546** [comment]
Looks like TVG is blocking IPs.  Recommend changing the "EPG Plugin to Use" to None for now.

**Comment by CheekyMunky81** [comment]
not sure if this is fixed or we just leave daddylive epg off?
